### ISSUE TITLE
Text Problem when converting SVG to PNG on AWS Lambda

### ISSUE THREAD

**Issue by droegier** [lovell/sharp#1875]
**What is the output of running `npx envinfo --binaries --languages --system --utilities`?**
My code is running on AWS Lambda Node 10, so I can not invoke this command.

**What are the steps to reproduce?**
On AWS Lambda I run the following function :

```
...
exports.handler = async function(event) {
  const result = await sharp("/tmp/ImageTemplateBis.svg").png().toBuffer();
  return {
    statusCode: 200,
    headers: {
      'Content-Type': 'image/png' 
    },
    body: result.toString('base64'),
    isBase64Encoded: true
  }
```
It works. The following image is returned. But the text rendering fails (I get rectangles instead of letters)
![image](https://user-images.githubusercontent.com/16133184/65145732-1fd79780-da12-11e9-833e-a957d4e0b185.png)

**What is the expected behaviour?**
Running this code locally (on Mac) and storing it to a file results in the following png with pretty letters : 
![image](https://user-images.githubusercontent.com/16133184/65145666-ff0f4200-da11-11e9-831c-f4f5f1af1d60.png)

I attached the `svg` in case this helps.
[ImageTemplateBis.svg.zip](https://github.com/lovell/sharp/files/3626185/ImageTemplateBis.svg.zip)

Thank you!

**Comment by lovell** [comment]
The salient part of the attached SVG file is:
```css
            @font-face {
                font-family: Merriweather;
                src: './fonts/Merriweather-Bold.ttf'';
            },
            @font-face {
                font-family: Source Sans Pro;
                src: './fonts/SourceSansPro-Regular.ttf'';
            }
```
You'll need to ensure fontconfig can find these two fonts in the Lambda environment - see #1565 for a previous example of a similar question.

**Comment by mooyoul** [comment]
I just deployed your sample with font files and can see proper render result.

<img width="1553" alt="스크린샷 2019-09-29 오후 12 58 22" src="https://user-images.githubusercontent.com/2101743/65826009-ed9f2300-e2b8-11e9-9e15-9f58abec05f8.png">
<img width="1019" alt="스크린샷 2019-09-29 오후 12 58 06" src="https://user-images.githubusercontent.com/2101743/65826010-ed9f2300-e2b8-11e9-8780-855fadb45251.png">

I had not to set any special configurations (e.g. fontconfig related environment setup) to render these results.

To @lovell : I can confirm this is not sharp's issue, nor AWS Lambda's environment issue. You can close this issue ;)

**Comment by droegier** [comment]
@mooyoul what OS and sharp version are you running?

**Comment by droegier** [comment]
I got rid of all font customisation by replacing all font-families in the `svg` by sans-serif.

Then I ran the above on lambda using `sharp 0.23.0`. Still get the same result. 

Putting `FC_DEBUG=1` I get, `Fontconfig error: Cannot load default config file`. 

So I assume the problem has not to do with **sharp**, and we can indeed close this issue. 

Would appreciate anything that sends me in the right direction though. AWS & FontConfig or rather librsvg?

**Comment by mooyoul** [comment]
I'm using macOS Mojave 10.14.6, Node.js v8.14.0, NPM v6.11.3, Serverless v1.43.0 as default development environment.

I installed sharp with `env npm_config_arch=x64 npm_config_platform=linux npm_config_target=8.10.0 npm i sharp@latest`. and bundled font files to deployment package.

Here is provable project: https://test-mooyoul.s3-accelerate.amazonaws.com/public/sharp-issue-1875.zip

and full screen cast: https://asciinema.org/a/GnVxF3eVZiffcURn6Iul5ZZli

I never configured any fontconfig related environment variable.

**Comment by mooyoul** [comment]
BTW, If your svg input location is `/tmp/ImageTemplateBis.svg`, font files should be located in `/tmp/fonts` (e.g. `/tmp/fonts/SourceSansPro-Regular.ttf ` for Source Hans Pro)

**Comment by lovell** [comment]
@droegier The `FONTCONFIG_PATH` environment variable can be used to provide fontconfig with an alternative location for its config file - see https://www.freedesktop.org/software/fontconfig/fontconfig-user.html#AEN266

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further help is required.

**Comment by brandonros** [comment]
```
@font-face {
        font-family: "Intervar";
        src: url("data:font/woff2;base64,d09GM...") format("woff2");
        font-weight: 600;
        font-style: normal;
      }
```
What about when you want to go the base64 route?

**Comment by MattGohr** [comment]
THANKS!  Figured it out!  Going to add my input here on how I got this to work incase anyone else is having trouble rendering fonts in AWS Lambda like this ticket describes.  Also thanks to @lovell for being super responsive to all of the tickets and keeping up with the project.  

Since the aws lambda environment doesn't seem like it has fonts, you have to download them, package them up with your project and reference the path to them (so sharp can get to them) with the `FONTCONFIG_PATH` env set to where the fonts will be.

So need to create a font.conf file that has this XML in it, in the same folder where you store the fonts.  I stored mine in a folder called `fonts` 

`<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>/var/task/fonts/</dir>
  <cachedir>/tmp/fonts-cache/</cachedir>
  <config></config>
</fontconfig>`

Then in your function set the font path to this:
process.env.FONTCONFIG_PATH='/var/task/fonts'

the `var/task/` path is where your lambda function lives on the aws lambda container. So you just need to create a folder in you project called `fonts` and put this font.conf file in it along with a font file.  And boom, you've got fonts with your shiney new PNG image.

**Note**: that the font file has to be a `.ttf` font file type like Roboto-Regular.ttf from google fonts.

**Comment by corybill** [comment]
@MattGohr First of all THANK YOU!!!!!!!!!!!

Second, its `fonts.conf` not `font.conf`.  Can you please update your post. Thanks.

**Comment by hutch120** [comment]
Hi All, Took me a while to figure this out, so I thought I'd add a couple of notes that might be helpful for others following along here to get this working on AWS lambda with serverless.

I'm using `serverless` with the `serverless-plugin-typescript` and needed to add the following to my `serverless.yaml` script to actually package and deploy the fonts folder and set the environment variable FONTCONFIG_PATH.

`serverless.yaml` (extract)

```
plugins:
  - serverless-plugin-typescript
package:
  patterns:
    - 'fonts/**'
environment:
    FONTCONFIG_PATH: /var/task/fonts
```

As mentioned above, I put the file `fonts.conf` in a sub folder called `fonts` (along with all the ttf fonts)

`/fonts/fonts.conf`

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>/var/task/fonts/</dir>
  <cachedir>/tmp/fonts-cache/</cachedir>
  <config></config>
</fontconfig>
```

To be super clear with the folder structure.

```
package.json
/fonts
-> /fonts.conf
-> /Aldrich-Regular.ttf  <== The font-family is Aldrich
-> /Audiowide-Regular.ttf <== The font-family is Audiowide
```

As for the SVG, I did not need to add any of the `font-face` stuff I saw in some other examples. I am generating SVG dynamically similar to this:

```
const positionY = 100
const positionX = 100
const layer3Buffer = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350">
        <text x="${positionX}" y="${positionY}" font-size="50" font-family="Aldrich">ABC</text>
    </svg>`)
const buffer = await sharp(svgBuffer).png().toBuffer() // buffer can be passed to S3 putObject.
```

Hope this helps.

References:
- https://www.serverless.com/framework/docs/providers/aws/guide/packaging
- https://stackoverflow.com/questions/46486261/include-custom-fonts-in-aws-lambda
- https://github.com/serverless/serverless-plugin-typescript#readme
- https://www.serverless.com/framework/docs/providers/aws/guide/variables
- https://fonts.google.com/specimen/Aldrich
- https://fonts.google.com/specimen/Audiowide
- https://stackoverflow.com/questions/16788330/how-do-i-get-the-font-name-from-an-otf-or-ttf-file

**Comment by gkostov** [comment]
> brandonros

I tried with a `base64` encoded data url but had no luck with that. Only after I installed the font locally did it work. Fortunately I did not need to remove the `@font-face` declaration so it still gets used in supporting environments (I use the same SVG file in various places) and Sharp simply ignores it.

That is on Ubuntu 20 with librsvg 2.48.9

Cheers

**Comment by dzocespd** [comment]
I know that this issue is closed for some time, but all the previous comments helped me to solve the same exact issue. 
The only difference that I had is that I have docker image of the app and I had to also install `fontconfig`.

In the dockerfile
```
# Install Fontconfig in the final runtime image
RUN dnf update -y && \
    dnf install -y fontconfig && \
    dnf clean all
```
