### ISSUE TITLE
GLib-GObject-CRITICAL G_IS_VALUE

### ISSUE THREAD

**Issue by Zewy** [lovell/sharp#216]
Do the GLib-GObject crash? the error log just gets filled with this for 1000 of lines then all is fine

```
(sharp:4364): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gtype.c:4206: type id `0' is invalid

(sharp:4364): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:4364): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with type `(null)', this t$

(sharp:4364): GLib-GObject-CRITICAL **: g_value_copy: assertion `G_IS_VALUE (src_value)' failed


(sharp:4364): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gtype.c:4206: type id `0' is invalid

(sharp:4364): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:4364): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with type `(null)', this t$

(sharp:4364): GLib-GObject-CRITICAL **: g_value_copy: assertion `G_IS_VALUE (src_value)' failed

(sharp:4364): GLib-GObject-CRITICAL **: g_value_unset: assertion `G_IS_VALUE (value)' failed


(sharp:4364): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:4364): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with type `(null)', this t$

(sharp:4364): GLib-GObject-CRITICAL **: g_value_copy: assertion `G_IS_VALUE (src_value)' failed

(sharp:4364): GLib-GObject-CRITICAL **: g_value_unset: assertion `G_IS_VALUE (value)' failed

(sharp:4364): GLib-GObject-CRITICAL **: g_value_unset: assertion `G_IS_VALUE (value)' failed

(sharp:4364): GLib-GObject-CRITICAL **: g_value_unset: assertion `G_IS_VALUE (value)' failed

(sharp:4364): GLib-GObject-CRITICAL **: g_value_unset: assertion `G_IS_VALUE (value)' failed

(sharp:4364): GLib-GObject-CRITICAL **: g_value_unset: assertion `G_IS_VALUE (value)' failed

(sharp:4364): GLib-GObject-CRITICAL **: g_value_unset: assertion `G_IS_VALUE (value)' failed

(sharp:4364): GLib-GObject-CRITICAL **: g_value_unset: assertion `G_IS_VALUE (value)' failed

**Comment by lovell** [comment]
Are you able to reproduce this consistently, perhaps for one particular image?

A possible cause might be a `glib` version mismatch. The `glib2.0-2.33.12+really2.32.4` version number and presence of `/tmp` in the filename both look a bit suspect. Is the version of glib that libvips was compiled against the same version being used at runtime?

**Comment by Zewy** [comment]
It just happens randomly two times a day. and my /tmp/ dir is empty so don't know way it even say that at all.

```
ii  gir1.2-glib-2.0                    1.32.1-1                      amd64        Introspection data for GLib, GObject, Gio and GModule
ii  libglib2.0-0:amd64                 2.33.12+really2.32.4-5        amd64        GLib library of C routines
ii  libglib2.0-bin                     2.33.12+really2.32.4-5        amd64        Programs for the GLib library
ii  libglib2.0-data                    2.33.12+really2.32.4-5        all          Common files for GLib library
ii  libglib2.0-dev                     2.33.12+really2.32.4-5        amd64        Development files for the GLib library
ii  libv8-3.14.5                       3.14.5.8-8~bpo70+1            amd64        V8 JavaScript engine - runtime library


Package: libglib2.0-0
State: installed
Automatically installed: yes
Multi-Arch: same
Version: 2.33.12+really2.32.4-5
Priority: optional
Section: libs
Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 4,009 k
Depends: libc6 (>= 2.9), libffi5 (>= 3.0.4), libpcre3 (>= 8.10), libselinux1 (>= 1.32), zlib1g (>= 1:1.2.2)
PreDepends: multiarch-support
Recommends: libglib2.0-data, shared-mime-info
Breaks: gvfs (< 1.8)
Replaces: libglib2.0-dev (< 2.23.2-2)
Description: GLib library of C routines
 GLib is a library containing many useful C routines for things such as trees, hashes, lists, and strings.  It is a useful general-purpose C library used by
 projects such as GTK+, GIMP, and GNOME.

 This package contains the shared libraries.
Homepage: http://www.gtk.org/


Package: libv8-3.14.5
New: yes
State: installed
Automatically installed: yes
Version: 3.14.5.8-8~bpo70+1
Priority: optional
Section: libs
Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Architecture: amd64
Uncompressed Size: 4,301 k
Depends: libc6 (>= 2.4), libgcc1 (>= 1:4.1.1), libstdc++6 (>= 4.1.1)
Description: V8 JavaScript engine - runtime library
 V8 is a high performance JavaScript engine written in C++.  It is used in the web browser Chromium.

 This package provides the dynamic library for V8.
Homepage: http://code.google.com/p/v8/

**Comment by lovell** [comment]
If it doesn't segfault the process and everything appears to keep working then I'd probably ignore it. We can leave this issue open in case anyone else experiences the same problem.

If it does segfault the process, a backtrace via something like the `catchsegv` command is our friend.

**Comment by Zewy** [comment]
I see that supervisor restart it one or two times a day. But It don't show why it restarted.

Here is my supervisor conf for the sharp what should I add to get catchsegv to work with it?

```[program:img]
command=/usr/bin/node /home/node/image.js
directory=/home/node
autostart=true
autorestart=true
stderr_logfile=/var/log/nodejs.img.err.log
stdout_logfile=/var/log/nodejs.img.out.log
user=www-data

**Comment by lovell** [comment]
Once you've installed `catchsegv`, modify the command to:
```
command=catchsegv /usr/bin/node /home/node/image.js
```
You should see a backtrace in the error log if the process segfaults.

**Comment by Zewy** [comment]
On my debian7 catchsegv was in the ```libc-bin``` so I need to do this instead.

```
command=/usr/bin/catchsegv /usr/bin/node /home/node/image.js
```
Where can I find the log from catchsegv?

**Comment by Zewy** [comment]
Here is my Supervisor log
```
2015-05-10 19:48:09,867 INFO exited: img (terminated by SIGSEGV; not expected)
2015-05-10 19:48:10,884 INFO spawned: 'img' with pid 22026
2015-05-10 19:48:12,374 INFO success: img entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

2015-05-12 22:39:27,586 INFO exited: img (terminated by SIGSEGV; not expected)
2015-05-12 22:39:28,596 INFO spawned: 'img' with pid 31755
2015-05-12 22:39:29,949 INFO success: img entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by lovell** [comment]
@Zewy Were you able to get any backtraces in the stderr or stdout logs?

**Comment by Zewy** [comment]
No I was unable to find where catchsgv is saving the log.

**Comment by lovell** [comment]
Sorry Zewy, not sure I can do much more to help here without a backtrace.

Perhaps it's time for you to ask Stack Overflow about the lack of catchsegv logging? Here's the best related question/answer I can find - http://stackoverflow.com/questions/77005/how-to-generate-a-stacktrace-when-my-gcc-c-app-crashes/6599348#6599348 - one of the other answers could help you.

**Comment by Zewy** [comment]
Checking it out, I replay as soon I have something logged.

**Comment by Zewy** [comment]
It crashed again and I got nothing to go on only this. I wish I know what image it was working on when it happened.
```

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gtype.c:4206: type id `0' is invalid

(sharp:31753): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with type `(null)', this type has no GTypeValueTable implementation

(sharp:31753): GLib-GObject-CRITICAL **: g_value_copy: assertion `G_IS_VALUE (src_value)' failed

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gtype.c:4206: type id `0' is invalid

(sharp:31753): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with type `(null)', this type has no GTypeValueTable implementation

(sharp:31753): GLib-GObject-CRITICAL **: g_value_copy: assertion `G_IS_VALUE (src_value)' failed

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gtype.c:4206: type id `0' is invalid

(sharp:31753): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with type `(null)', this type has no GTypeValueTable implementation

(sharp:31753): GLib-GObject-CRITICAL **: g_value_copy: assertion `G_IS_VALUE (src_value)' failed

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gtype.c:4206: type id `0' is invalid

(sharp:31753): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with type `(null)', this type has no GTypeValueTable implementation

(sharp:31753): GLib-GObject-CRITICAL **: g_value_copy: assertion `G_IS_VALUE (src_value)' failed

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gtype.c:4206: type id `0' is invalid

(sharp:31753): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:31753): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with type `(null)', this type has no GTypeValueTable implementation

(sharp:31753): GLib-GObject-CRITICAL **: g_value_copy: assertion `G_IS_VALUE (src_value)' failed

**Comment by Zewy** [comment]
Got this warning also now haven't got that before
I have this settings for sharp
sharp.cache(2048,1024);
sharp.concurrency(4);
Is there any other settings I should add? sharp process around 50/s jpg images a sec and there size is from 50 to 200KB under normal load. Sometimes it is around 300/s+ but it is rare occasions.

Going to test with Apache JMeter and check out if it is high load that makes it crash.

```
vips warning: linecache: error reading tile 0x0: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x8: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x16: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x24: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x32: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x40: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x48: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x56: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x64: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x72: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x80: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x88: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x96: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x104: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x112: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x120: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x128: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x136: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x144: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x152: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x160: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x168: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x176: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x184: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x192: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x200: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x208: VipsJpeg: out of order read at line 1120

vips warning: linecache: error reading tile 0x216: VipsJpeg: out of order read at line 1120

**Comment by lovell** [comment]
"out of order read" looks like https://github.com/jcupitt/libvips/issues/261, fixed in (I think) libvips 8.0.1.

**Comment by lovell** [comment]
@Zewy Are you still experiencing this problem? If so, were you able to extract a backtrace?

**Comment by Zewy** [comment]
@lovell Sorry still unable to get any backtrace from it.
Here is what I was able to to get from last crash. it just takes less then 1 sec to restart it so it not a so big issue.

```
Supervisor log
---
2015-05-21 23:00:01,847 INFO exited: img (terminated by SIGSEGV; not expected)
2015-05-22 14:52:55,005 INFO exited: img (terminated by SIGSEGV; not expected)
2015-05-28 08:14:32,935 INFO exited: img (terminated by SIGSEGV; not expected)
2015-06-04 20:43:52,141 INFO exited: img (terminated by SIGSEGV; not expected)
2015-06-10 10:04:39,051 INFO exited: img (terminated by SIGSEGV; not expected)
2015-06-19 18:32:26,489 INFO exited: img (terminated by SIGSEGV; not expected)
2015-06-25 23:08:52,236 INFO exited: img (terminated by SIGSEGV; not expected)
---

nodejs log
---
2015-06-25 21:32:29 Uptime: 147
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: read gave 2449 warnings
vips warning: VipsJpeg: Premature end of JPEG file
VipsJpeg: JPEG datastream contains no image

2015-06-25 22:32:29 Uptime: 148
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: read gave 1 warnings
vips warning:

(sharp:21591): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gtype.c:4206: type id `0' is invalid

(sharp:21591): GLib-GObject-WARNING **: can't peek value table for type `<invalid>' which is not currently referenced

(sharp:21591): GLib-GObject-WARNING **: /tmp/buildd/glib2.0-2.33.12+really2.32.4/./gobject/gvalue.c:192: cannot initialize GValue with
 type `(null)', this type has no GTypeValueTable implementation
vips warning: VipsJpeg: read gave 2 warnings
vips warning:
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
vips warning: VipsJpeg: error reading resolution
2015-06-26 00:08:55 Uptime: 1
2015-06-26 01:08:55 Uptime: 2
---

**Comment by jcupitt** [comment]
Can you set environment variables for your client processes? A useful one is `setenv G_DEBUG=fatal-warnings`, this will make the process `abort()` (and hopefully generate a stack trace) on the first warning message.

**Comment by Zewy** [comment]
@jcupitt going to add that line to my supervisor, do you know if I need something more then this?
```
[program:img]
command=/usr/bin/catchsegv /usr/bin/node /home/node/image.js
directory=/home/node
autostart=true
autorestart=true
stderr_logfile=/var/log/nodejs.img.err.log
stdout_logfile=/var/log/nodejs.img.out.log
user=www-data
environment=G_DEBUG="fatal-warnings"

**Comment by jcupitt** [comment]
Sorry, I don't use supervisor :( but I'd guess that might work.

**Comment by lovell** [comment]
Closing due to a lack of updates but please do add comments or re-open if this problem still exists.

**Comment by Alex-Werner** [comment]
Hi ! 
See this log : 
![image](https://user-images.githubusercontent.com/5849920/27049512-e175f41c-4faf-11e7-944e-3fad9a615bb8.png)
using : "sharp": "^0.18.1", didn't saw that issue before (I do not have the image as it was on production).

**Comment by lovell** [comment]
@Alex-Werner Are you using node-canvas in the same process?

**Comment by Alex-Werner** [comment]
Not that I'm aware of but maybe in submodules ?

```
"dependencies": {
    "amqplib": "^0.5.1",
    "asyncawait": "^1.0.6",
    "bluebird": "^3.5.0",
    "boom": "^4.1.0",
    "chai": "^3.5.0",
    "check-types": "^7.1.5",
    "eventemitter2": "^3.0.2",
    "fs-extra": "^2.1.2",
    "hapi": "^16.3.0",
    "hapi-auth-cookie": "^6.1.1",
    "hapi-cron-job": "^2.0.1",
    "hoek": "^4.1.1",
    "htmlparser2": "^3.9.2",
    "inert": "^4.2.0",
    "joi": "^10.5.2",
    "jssha": "^2.3.0",
    "khal": "^2.0.0",
    "later": "^1.2.0",
    "lodash": "^4.17.4",
    "lout": "^9.1.0",
    "mandrill-api": "^1.0.45",
    "microwork": "^0.12.0",
    "microwork-rpc-handler": "^1.0.2",
    "moment": "^2.18.1",
    "mongodb": "^2.2.27",
    "node-gcm": "^0.14.6",
    "node-sass": "^3.8.0",
    "nodemailer": "^2.7.0",
    "object-assign": "^4.1.1",
    "request": "^2.81.0",
    "sha3": "^1.2.0",
    "sharp": "^0.18.1",
    "shortid": "^2.2.8",
    "vision": "^4.1.1",
    "winston": "^2.3.1"
  },
```

**Comment by lovell** [comment]
Thanks, my money would be on node-sass, which depends on libsass which depends on glib.

If so, a couple of options are:

1. ensure sharp is `require`'d before node-sass, or vice versa.
2. use a global install of both libsass and libvips

**Comment by karlpatrickespiritu** [comment]
Hi not using any node-sass. But getting this issue:

```
(sharp:1265): GLib-GObject-WARNING **: gtype.c:4273: type id '0' is invalid

(sharp:1265): GLib-GObject-WARNING **: can't peek value table for type '<invalid>' which is not currently referenced

(sharp:1265): GLib-GObject-WARNING **: gvalue.c:184: cannot initialize GValue with type '(null)', this type has no GTypeValueTable implementation

(sharp:1265): GLib-GObject-CRITICAL **: g_value_transform: assertion 'G_IS_VALUE (dest_value)' failed
```

Only getting this randomly. Most of the time the resizer works just fine.
