### ISSUE TITLE
TIFF format to/from Buffer, requires libvips v8.5.2+

### ISSUE THREAD

**Issue by strarsis** [lovell/sharp#587]
I cannot find a tif(f)() output method, also toFormat('tiff')/toFormat('tif') results in error:

```
[Error: Unsupported output format tif(f)]
```

It would be great if sharp supports tiff as output format, too.

**Comment by lovell** [comment]
Hello, TIFF output is limited to filesystem only - use something like `toFile('file.tif', ...)` to access this feature.

**Comment by strarsis** [comment]
I have to use the extra steps reading/writing the file (using fs module) 
because of the issue with special characters in path.

**Comment by lovell** [comment]
> "the issue with special characters in path"

This has been fixed in libvips 8.4.x - see https://github.com/jcupitt/libvips/issues/294

**Comment by strarsis** [comment]
Do I have to install/build the newer libvips myself or is it shipped/built by sharp package?
I still have this issue on windows + linux - see this test: https://github.com/strarsis/sharp-issue-characters/

Besides, it would be still helpful if TIFF could be obtained as buffer for 
further processing in-memory without the need of a temporary files.

**Comment by lovell** [comment]
The next major version of sharp, v0.17.0, will be bundled with a pre-compiled libvips v8.4.x+.

> "it would be still helpful if TIFF could be obtained as buffer"

You'll need to add tiffload_buffer (and tiffsave_buffer) support to [libvips](https://github.com/jcupitt/libvips), then expose the feature in sharp. If you're willing to work on this and submit a PR then I'm sure John will help.

**Comment by lovell** [comment]
See https://github.com/jcupitt/libvips/issues/417

**Comment by strarsis** [comment]
Thanks!

**Comment by lovell** [comment]
I'll assume you intended to close this, feel free to re-open if not.

**Comment by felixbuenemann** [comment]
@lovell John implemented `tiffsave_buffer` in master and it should be included in vips 8.5.

**Comment by lovell** [comment]
@felixbuenemann Thanks, will re-open and mark as a future enhancement.

**Comment by lovell** [comment]
Commit c8e59f0 on the [ridge](https://github.com/lovell/sharp/tree/ridge) branch adds Buffer and Stream based TIFF output. This will be in v0.18.0.

**Comment by lovell** [comment]
v0.18.0 now available with this feature.
